name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker for Client
      uses: actions/setup-docker@v2
      with:
        dockerfile: ./client/Dockerfile
        context: ./client

    - name: Build and Push Docker Image for Client
      run: |
        docker build -t nairod36/client-image:latest .
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push nairod36/client-image:latest

    - name: Set up Docker for Server
      uses: actions/setup-docker@v2
      with:
        dockerfile: ./server/Dockerfile
        context: ./server

    - name: Build and Push Docker Image for Server
      run: |
        docker build -t nairod36/server-image:latest .
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push nairod36/server-image:latest

  # deploy:
  #   runs-on: ubuntu-latest

  #   needs: build

  #   steps:
  #   - name: Set up SSH
  #     uses: webfactory/ssh-agent@v0.5.4
  #     with:
  #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

  #   - name: Checkout Repository
  #     uses: actions/checkout@v2

  #   - name: Deploy Docker Compose for Client and Server
  #     run: |
  #       scp -r ./client/docker-compose.yml your-ssh-user@your-server-ip:~/path/to/remote/directory/client/
  #       scp -r ./server/docker-compose.yml your-ssh-user@your-server-ip:~/path/to/remote/directory/server/
  #       ssh your-ssh-user@your-server-ip "cd ~/path/to/remote/directory/client/ && docker-compose pull && docker-compose up -d"
  #       ssh your-ssh-user@your-server-ip "cd ~/path/to/remote/directory/server/ && docker-compose pull && docker-compose up -d"
